# Generated by Django 4.0.6 on 2022-07-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('pub_date', models.DateField()),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
    ]
